[tool.poetry]
name = "nfl"
version = "0.1.0"
description = ""
authors = ["Jinfeng Chen <89889912+tepzoid@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
